### ISSUE TITLE
BCDTo7Seg Library not working

### ISSUE THREAD

**Issue by shazinmoh** [danielbcorreia/BCDTo7Seg#1]
When I try to verify or upload this error pops up. Please help. Thanks

Arduino: 1.6.13 (Windows Store 1.6.13.0) (Windows 10), Board: "Arduino/Genuino Uno"

In file included from C:\Users\Shazin\AppData\Local\Temp\arduino_modified_sketch_262457\b4511_counter.pde:1:0:

C:\Users\Shazin\Documents\Arduino\libraries\BCDTo7Seg/BCDTo7Seg.h:4:22: fatal error: WProgram.h: No such file or directory

 #include "WProgram.h"

                      ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
![untitled](https://cloud.githubusercontent.com/assets/25004028/21761968/2b0b80cc-d67c-11e6-80a5-18ea861953d9.png)

**Comment by danielbcorreia** [comment]
Fixed in latest version.

Commit: https://github.com/danielbcorreia/BCDTo7Seg/commit/112ed3acb0d280c09a342680cce5356de681f7c4
